export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_SIGN_UP_LOADING = "USER_SIGN_UP_LOADING";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_ERROR = "USER_SIGN_UP_ERROR";

export const USER_FORGOTPASS_LOADING = "USER_FORGOTPASS_LOADING";
export const USER_FORGOTPASS_SUCCESS = "USER_FORGOTPASS_SUCCESS";
export const USER_FORGOTPASS_ERROR = "USER_FORGOTPASS_ERROR";

export const USER_ACCOUNT_DETAILS_LOADING = "USER_ACCOUNT_DETAILS_LOADING";
export const USER_ACCOUNT_DETAILS_SUCCESS = "USER_ACCOUNT_DETAILS_SUCCESS";
export const USER_ACCOUNT_DETAILS_ERROR = "USER_ACCOUNT_DETAILS_ERROR";

export const USER_ACCOUNT_UPDATE_LOADING = "USER_ACCOUNT_UPDATE_LOADING";
export const USER_ACCOUNT_UPDATE_SUCCESS = "USER_ACCOUNT_UPDATE_SUCCESS";
export const USER_ACCOUNT_UPDATE_ERROR = "USER_ACCOUNT_UPDATE_ERROR";

export const USER_LOGOUT_LOADING = "USER_LOGOUT_LOADING";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

