export const OPERATE_NOTIFICATION_LOADING = "OPERATE_NOTIFICATION_LOADING";
export const OPERATE_NOTIFICATION_SUCCESS = "OPERATE_NOTIFICATION_SUCCESS";
export const OPERATE_NOTIFICATION_ERROR = "OPERATE_NOTIFICATION_ERROR";
