export const OPERATE_SETTINGS_LOADING = "OPERATE_SETTINGS_LOADING";
export const OPERATE_SETTINGS_SUCCESS = "OPERATE_SETTINGS_SUCCESS";
export const OPERATE_SETTINGS_ERROR = "OPERATE_SETTINGS_ERROR";
