// customers
export const OPERATE_STUDENT_LOADING = "OPERATE_STUDENT_LOADING";
export const OPERATE_STUDENT_SUCCESS = "OPERATE_STUDENT_SUCCESS";
export const OPERATE_STUDENT_ERROR = "OPERATE_STUDENT_ERROR";
