export const OPERATE_SUB_ADMIN_LOADING = "OPERATE_SUB_ADMIN_LOADING";
export const OPERATE_SUB_ADMIN_SUCCESS = "OPERATE_SUB_ADMIN_SUCCESS";
export const OPERATE_SUB_ADMIN_ERROR = "OPERATE_SUB_ADMIN_ERROR";
