export const OPERATE_TRANSATIONS_LOADING = "OPERATE_TRANSATIONS_LOADING";
export const OPERATE_TRANSATIONS_SUCCESS = "OPERATE_TRANSATIONS_SUCCESS";
export const OPERATE_TRANSATIONS_ERROR = "OPERATE_TRANSATIONS_ERROR";
